[package]
name = "localghost-hello-world"
version = "0.1.0"
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]

[dependencies]
localghost = { path = "../.." }

[dev-dependencies]
wasm-bindgen-test = "0.3.5"
